"use client"
import React, { useState, useEffect } from 'react'
import {motion} from 'framer-motion'
import NavMenu from '../../landcomp/navmenu'
import Footer from '../../landcomp/footer'
export default function LandingPage(){
return (
<main>
    <div className="flex justify-center items-center p-4 m-[3rem]"><NavMenu/></div>
        <h1 className="text-7xl font-bold text-center text-black relative z-20">
            Dialai MTA
        </h1>
    <div className='hidden md:flex'>
        <div className="flex justify-center items-center w-full h-screen overflow-hidden relative">
            <p className="text-red-500">
                    This content is only viewable on Desktop devices. 
            </p>
            <iframe
            src="https://hexronus-portfolio.hf.space"
            className="w-full h-[200%] max-w-[850px] max-h-[650px] border-none absolute"
            style={{
            bottom: "10%",
            clipPath: "inset(0 0 0 0)",   
            }} 
            allowFullScreen
            >
            </iframe>
            <div className="absolute bottom-0 w-full bg-white text-center p-4">
                <p className="text-red-500">
                Note: Due to server reboot, the every first start will take quite a bit of time to load as the CPU reboots and loads the value each time. 
                </p> 
            <div className="text-sm md:text-base text-left pt-2 py-4 m-4 text-gray-800 mb-6">
                     <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                         <strong className="font-bold">Disclaimer: </strong>
                                 <span className="block sm:inline">The content generated by this AI is not controlled by anyone and the user has full responsibility for its use. This AI does not use any content filters, so it may produce inappropriate or nonsensical content. Please use responsibly.</span>
                             </div>
                       </div>
                     </div>
                </div>
            </div>
                        <div className='flex justify-center md:hidden'>
            <div className="text-sm md:text-base text-left pt-2 py-4 m-4 text-gray-800 mb-6">
                <div className="bg-yellow-100 border border-yellow-400 text-yellow-700 px-4 py-3 rounded relative" role="alert">
                        <strong className="font-bold">Disclaimer: </strong>
            <span className="block sm:inline">This content is only available for desktop sized deviced due to some reasons (as of now), it'll be quickly shifted to all sized windows very soon.</span>
                </div>
                </div>
</div>
<motion.div
className="flex items-center justify-center gap-4 text-lg font-semibold text-gray-800 my-5"
initial={{ y: -50, opacity: 0 }}
animate={{ y: 0, opacity: 1 }}
transition={{ duration: 0.5 }}
>
<Footer/>
</motion.div>
</main>
)
}